### ISSUE TITLE
nothing showing when using the prefab

### ISSUE THREAD

**Issue by nathanleggett** [Thryrallo/UdonPrefabs#1]
so i was just trying this out to see what sort of menu system it is. ive dragged the prefab into my world but on testing i see no menu at all

**Comment by dragonash2019** [comment]
The menu system works 100% of the time from desktop pressing "M", but maybe 1 in 20 times when swiping in VR.
I've gone back to your world and it works flawlessly. It barely works in mine.

Also, would it be possible to include your world as a scene so we can inspect how you set the prefab up?

**Comment by dragonash2019** [comment]
@nathanleggett This is fixed. Worked with Thry for a bit and he uploaded a new build. Currently works in my world.

**Comment by Thryrallo** [comment]
Maybe I should add a readme, but in the vrcs prefabs database there's a link to a video showing how it's used.
On desktop press m.
In vr swipe dowm
