### ISSUE TITLE
Mirror button not working

### ISSUE THREAD

**Issue by advanced4** [Thryrallo/UdonPrefabs#4]
I've been playing around with the menu a bunch but cannot get the mirror to work. Just retested on an unmodified version of the SAO Menu Full Feature prefab from the 1.0.3 package. I did see it spawn outside a window in my world, kind of far from the player, and the mirror was giant once though (?)

**Comment by Thryrallo** [comment]
The mirror button opens a mirror based on where the player is looking. While the menu is open the possible mirror positions are indicated by this icon.
![image](https://user-images.githubusercontent.com/40315315/111921698-427abe80-8a96-11eb-89b4-b48721551f6a.png)
In unity you place those around your world. You can define the size of each mirror in the size transform (add a quad if you want a preview of how big the mirror will be)
![image](https://user-images.githubusercontent.com/40315315/111921693-3d1d7400-8a96-11eb-8760-d9a7077430b8.png)
The mirror manger also need references to all those mirror definitions
![image](https://user-images.githubusercontent.com/40315315/111921766-aef5bd80-8a96-11eb-820f-dc18f975dda3.png)

If you want to have just one simple mirror in the world you can replace the script on the mirror button with a method call one.

**Comment by advanced4** [comment]
Thanks! It wasn't clear to me how this worked, given the demo video showing a simple toggle mirror. This cleared things up & I got what I wanted working (simple mirror toggle)
