### ISSUE TITLE
Sao toggel

### ISSUE THREAD

**Issue by ImortalNexus** [Thryrallo/UdonPrefabs#5]
so i was wondering is there a way to control objects such as toggling a pool table or music from the sao menu?
i was also wondering if theres a way to make a button in the menu that respawns items

**Comment by Thryrallo** [comment]
Sorry for the late response. In the current version you can use "ThryAction" to set up a large number of action types.
Here an example:
![image](https://user-images.githubusercontent.com/40315315/149001882-b3efaaf7-082c-4617-ab83-7ec03523fdbd.png)
You have one ThryAction script. This defines what will actually be toggles / happen.
You have one ToggleAdapter (this is added automatically if a toggle UI element is on the gameobject). It will relay the information between the button and the ThryAction script.

In the ThryAction script, you can define GameObject Toggles, Collider Toggle, Pickup Toggles etc. and optionally make them synced.
There is currently no built in way to respawn items. You could use your own respawn script can call it via an Udon Call from ThryAction however.
