### ISSUE TITLE
Game can "crash" when ball goes twice times in same cup.

### ISSUE THREAD

**Issue by MrDummyNL** [Thryrallo/UdonPrefabs#6]
It just happened yesterday, but we saw it.
When the player throw the ball in the cup, it should removed soon.
But there is also some delay before cup is removed, and it just happened if player throw again ball in same cup.

The hit animation / particle effect is visible in both, and then we noticed the ball stays there. The script didn't detect it because cup was internal already disabled but not well synchronized to players for short time.
And that is it. The game is frozen, because the script cannot detect it anymore. We can try roll ball away over the edge table but still no detection. It's just dead, the ball just rolls over the floor away without reset.

So it's good idea to add extra checks to avoid this "double" hit problem where detection is disabled after first hit, and then game script does nothing for the ball. Dead.

**Comment by Thryrallo** [comment]
This was fixed in one of the latest updates.
