### ISSUE TITLE
Bottle Spinner text resets when in test mode or in-game!

### ISSUE THREAD

**Issue by Huey-Lewy** [Thryrallo/UdonPrefabs#9]
How do I change the pre-included text on the Bottle Spinner table?

I clicked through **Option1**  to **Option9** within the prefab, and then changed the text within the **TextMeshPro - Text**. While in edit mode in Unity, it shows that my changes have been applied. However, when I go into test mode (VRChat Emulator) or play in-game after uploading it, the custom text I have done resets back to the default pre-included text.

When I get out of test mode and look at it again in edit mode, it shows the custom text again.

**Comment by Thryrallo** [comment]
??? Please post some pictures. The bottle spin does not use TMPro so I am unsure what you are trying to change

**Comment by Huey-Lewy** [comment]
It seems that the version I have was... customize version of the prefab?
I'll go ahead and remove the weird version I have and try installing this Prefab instead

**Comment by Thryrallo** [comment]
in that case i will close this issue. feel free to reopen if you run into the same issue with the original prefab
